name: artvier
# _rixstal
# _staluno
# _kristalo
description: A third-party app for pixiv.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.3

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^4.0.7
  # app_links: ^6.4.1
  crypto: ^3.0.6
  # The following adds the Cupertino Icons font to your application.flutter_downloader
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  date_format: ^2.0.9
  # device_info_plus: ^10.1.2 # 设备信息
  dio: ^5.8.0+1
  drift: ^2.25.0 # 数据库
  extended_image: ^10.0.1 # 图片
  extended_nested_scroll_view: ^6.2.1
  extended_sliver: ^2.1.3
#  flutter_downloader: 1.7.0 # 文件下载
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.6.1 # 状态管理
  flutter_sticky_header: ^0.8.0 # 多个header的吸顶效果
  flutter_svg: ^2.2.0
  flutter_widget_from_html: ^0.17.0
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.4.4 # 模板代码生成
  go_router: ^16.2.1 # 路由
  html: ^0.15.6 # 解析 HTML
  # image_gallery_saver: ^2.0.3 # 图片保存，太久没更新，弃用
  image_gallery_saver_plus: ^4.0.1 # 图片保存
  image: ^4.5.4
  intl: ^0.20.2 # 国际化
  json_annotation: ^4.9.0
  logger: ^2.6.1 # 输出日志
  # package_info_plus: ^4.0.2 # 获取本App的信息
  modal_bottom_sheet: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1 # 权限管理
  package_info_plus: ^8.3.0
  photo_view: ^0.15.0 # 图片预览
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.37
  url_launcher: ^6.3.2 # 用于打开第三方应用
  visibility_detector: ^0.4.0+2 # 用于判断组件是否在视口内
  waterfall_flow: ^3.1.1 # 瀑布流
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.7.1
  build_runner: ^2.5.4 # 构建工具，命令：dart run build_runner build
  dart_style: ^2.3.8
  drift_dev: ^2.25.2
  lints: ^6.0.0
  flutter_lints: ^6.0.0
  freezed: ^2.5.8 # 模板代码生成工具
  intl_translation: ^0.20.1 # 国际化
  json_serializable: ^6.9.5 # json序列化
  source_gen: ^2.0.0 # 让工具生成的代码忽视lints

dependency_overrides:
  analyzer: '7.7.1'
  dart_style: ^2.3.8
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image/default_avatar.png
   - assets/image/page_loading.gif
   - assets/image/network_error.png
   - assets/icon/
   - assets/emoji/
   - assets/sticker/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
