name: artvier
# _rixstal
# _staluno
# _kristalo
description: A third-party app for pixiv.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.6.1
  crypto: ^3.0.1
  # The following adds the Cupertino Icons font to your application.flutter_downloader
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  date_format: ^2.0.2
  dio: ^5.4.2+1
  drift: ^2.17.0 # 数据库
  extended_image: ^8.0.2 # 图片
  extended_nested_scroll_view: ^6.0.0
  extended_sliver: ^2.1.3
#  flutter_downloader: 1.7.0 # 文件下载
#  flutter_staggered_grid_view: ^0.4.0
  flutter_riverpod: ^2.1.3 # 状态管理
  flutter_sticky_header: ^0.6.5 # 多个header的吸顶效果
  fluttertoast: ^8.0.8
  freezed_annotation: ^2.2.0 # 模板代码生成
  html: ^0.15.4 # 解析 HTML
  image_gallery_saver: ^2.0.3 # 图片保存
  image: ^4.2.0
  intl: ^0.18.0 # 国际化
  json_annotation: ^4.7.0
  logger: ^2.2.0 # 输出日志
  # package_info_plus: ^4.0.2 # 获取本App的信息
  path: ^1.9.0
  path_provider: ^2.0.1
  permission_handler: ^11.3.1 # 权限管理
  package_info_plus: ^6.0.0
  photo_view: ^0.14.0 # 图片预览
  provider: ^6.1.2
  shared_preferences: ^2.0.5
  sqlite3_flutter_libs: ^0.5.20
  url_launcher: ^6.2.5 # 用于打开第三方应用
  visibility_detector: ^0.4.0+2 # 用于判断组件是否在视口内
  waterfall_flow: ^3.0.1 # 瀑布流
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1
  build_runner: ^2.3.3 # 构建工具，命令：dart run build_runner build
  drift_dev: ^2.17.0
  flutter_lints: ^3.0.2
  freezed: ^2.3.2 # 模板代码生成工具
  intl_translation: ^0.19.0 # 国际化
  json_serializable: ^6.5.4 # json序列化
  source_gen: ^1.2.6 # 让工具生成的代码忽视lints
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image/default_avatar.png
   - assets/image/page_loading.gif
   - assets/image/network_error.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
